config/routes.rb
Rails.application.routes.draw do
  
  
  resources :storages
  devise_for :users

  get 'home/index'
  root to: "stores#index"
  resources :stores
  resources :books
  
  get 'probar', to: 'control#saludo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :store
  has_many :storage, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true
  validates :year, presence: true
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :store
  belongs_to :book
  
end

app/models/store.rb
class Store < ApplicationRecord

  belongs_to :user
  has_many :storage, dependent: :destroy
  validates :codename, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :stores
  belongs_to :user
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_devise_params, if: :devise_controller?

   def configure_devise_params
      devise_parameter_sanitizer.permit(:sign_up) do |user|
        user.permit(:name, :email, :password, :password_confirmation)
      end
    end
    def after_sign_out_path_for( resource_or_scope)
        new_user_session_path
     end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books 
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :year, :user_id)
    end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController

    def saludo
        @MyName = 'Carlos'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: [:show, :edit, :update, :destroy]


  def show
  end

  # GET /storages/new
  def new
    @books = current_user.books
    @store = Store.find(params[:id])
    @storage = @store.storage.new
    
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages
  # POST /storages.json
  def create
    @store = Store.find(params[:id])
    @storage = @store.storage.create(storage_params)
    respond_to do |format|

      if @storage.save
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to @storage, notice: 'Storage was successfully updated.' }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url, notice: 'Storage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def storage_params
      params.require(:storage).permit(:store_id, :book_id, :quantity)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy ]
  def index
    if current_user.present? 
      @stores = current_user.stores
    else
      @stores = Store.all
    end
  end

  def new 
    @store = Store.new
  end

  def create 
     
    @store = Store.new store_params
    @store.user = current_user
    if @store.save 
      redirect_to stores_path
    else
      render :new
    end
    
  end


  def show
    @storages = Store.find(params[:id]).storage
  end

  def edit
  end

  def update
    @store.update store_params
    redirect_to @store
  end

  def destroy 
    @store.destroy
    redirect_to stores_path
  end

  private
  def store_params
    params.require(:store).permit(:codename, :address, :Phone)
  end

  def set_store
    @store = Store.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.datetime_select :year %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book , {:class=>"btn btn-light"}%> |
<%= link_to 'Back', books_path,{:class=>"btn btn-light"}  %>

app/views/books/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>



<div class="container">

  <p id="notice"><%= notice %></p>

    <h1>Books</h1>

     <table class="table">
     <thead class="thead-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Year</th>
        <th scope="col">User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.year.strftime('%d-%m-%Y') %></td>
          <td><%= book.user.name %></td>
          <td><%= link_to 'Show', book, {:class=>"btn btn-light"} %></td>
          <td><%= link_to 'Edit', edit_book_path(book), {:class=>"btn btn-light"} %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book', new_book_path, {:class=>"btn btn-light"} %>
  <%= link_to 'back', stores_path, {:class=>"btn btn-light"} %>

</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path,{:class=>"btn btn-light"}  %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>User:</strong>
  <%= @book.user_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book), {:class=>"btn btn-light"} %> 
<%= link_to 'Back', books_path, {:class=>"btn btn-light"} %>

app/views/control/saludo.html.erb
<p> Hola como estas? </p> 
<p> Mi nombre es: <%= @MyName%> 

app/views/home/index.html.erb
<% if user_signed_in? %>
 <h1> Bienvenido a Tus librerias <%= current_user.name%> </h1>

<% else %>
 <h1> Adios :D </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Liberia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    </head>

  <body>
    <div class="container">

     <ul class="nav justify-content-end">
       <%- if user_signed_in? %>
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <li class="nav-item">
           <%= link_to 'AllBooks', books_path, {:class=>"nav-link"} %>
          </li>
          <li class="nav-item">
           <%= link_to 'Stores', stores_path, {:class=>"nav-link"} %>
          </li>
          <li class="nav-item">
           <%= link_to 'New Branch Office', new_store_path, {:class=>"nav-link"}%>
          </li>
          <li class="nav-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
          </li>



          <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar', new_user_session_path, {:class=>"btn btn-light"} %>
            </li>
            <li class="nav-item">
            <%= link_to 'Registrarme', new_user_registration_path, {:class=>"btn btn-light"} %>
            </li>
          <% end %>
       </nav>
        
     </ul>

     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>



    
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/storages/_form.html.erb
<%= form_with(model: storage, url: url, local: true) do |form| %>
  
  <% if storage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(storage.errors.count, "error") %> prohibited this storage from being saved:</h2>

      <ul>
        <% storage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   
  <div class="field">
    <%= form.label :book_id %>
    <%- if params[:action] == 'new' %>
      <%- books = @books.map { |book| [book.title, book.id]} %>
      <%= form.select :book_id, options_for_select(books) %>
    <%- else %>
      <p> <%= storage.book.title %> </p>
    <% end %>
  </div>

 

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/storages/edit.html.erb
<h1>Editing Storage</h1>

<%= render 'form', storage: @storage, url: storage_path(id: @storage.id) %>


<%= link_to 'Show', @storage , {:class=>"btn btn-light"} %> |
<%= link_to 'Back', book_path(@storage.book_id), {:class=>"btn btn-light"} %>

app/views/storages/new.html.erb
<h1>New Storage</h1>

<%= render 'form', storage: @storage, url: storages_path(id: params[:id]) %>

<%= link_to 'Back', books_path, {:class=>"btn btn-light"}%>

app/views/storages/show.html.erb
<div class="container">




 <p id="notice"><%= notice %></p>

 <p>
  <strong>Store:</strong>
  <%= @storage.store.codename %>
 </p>

 <p>
  <strong>Book:</strong>
  <%= @storage.book.title %>
 </p>

 <p>
  <strong>Quantity:</strong>
  <%= @storage.quantity %>
 </p>

 <%= link_to 'Edit', edit_storage_path(@storage, store_id: @storage.store_id), {:class=>"btn btn-light"} %> |
 <%= link_to 'Back', book_path(@storage.book_id), {:class=>"btn btn-light"}%>

 
</div>

app/views/stores/_form.html.erb
<%=  form_for @store do |f| %> <br>

    <%= f.label :codename %>
    <%= f.text_field :codename %><br>

    <%= f.label :Address %>
    <%= f.text_field :address %><br>

    <%= f.label :Phone %>
    <%= f.text_field :Phone %> <br>

    <%= f.submit %>

    

<% end %>

app/views/stores/_store.html.erb
<div class="container">



 <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col"><%= store.address%></th>
      <th scope="col"><%= store.codename%></th>
      <th scope="col"><%= store.Phone%></th>
      
    </tr>
  </thead>
 
  <%= link_to 'Edit', edit_store_path(store), {:class=>"btn btn-light"}%>
  <%= link_to 'Destroy', store, method: :delete, data: { confirm: 'sure?'}%>
  <%= link_to 'Register Books', new_storage_path(id: store.id), {:class=>"btn btn-light"}%>
  <%= link_to 'New book', new_book_path, {:class=>"btn btn-light"}%>
  <%= link_to 'Inventory', store_path(store), {:class=>"btn btn-light"}%>
  

  
</div>

app/views/stores/edit.html.erb
<p> Editar Imagen</p>

<%= render 'form' %> <br>

app/views/stores/index.html.erb
<%= render @stores %>
   

app/views/stores/new.html.erb
<h3> Add a new Branch Office:  </h3>

<%= render 'form' %> <br>

app/views/stores/show.html.erb
<h3><%= @store.address%></h3>
<h3><%= @store.codename%></h3> 
<h3><%= @store.Phone%></h3>

<table class="table">
     <thead class="thead-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Year</th>
        <th scope="col">Quantity</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @storages.each do |storage| %>
        <tr>
          <td><%= storage.book.title %></td>
          <td><%= storage.book.author %></td>
          <td><%= storage.book.year.strftime('%d-%m-%Y') %></td>
          <td><%= storage.quantity %></td>
          <td><%= link_to 'Edit', edit_storage_path(storage), {:class=>"btn btn-light"} %></td>
          <td><%= link_to 'Destroy', storage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>